dist: xenial

language: php

cache:
  directories:
    - $HOME/.composer/cache
env:
  global:
    secure: "a7MYYrKeOVDeTsYxwgwiQPwbIEyk4jfktwdf9yzCb24kh6jw9SNrZb4aENUDNX9X7hMoD8d+tZLvASIn1DcDLAg+PJFlCgxtx/Jo8my5qbOPFaP9T4juRvhVjcktzg0puiEaNkehbzqcFrTMKKZTT2b+I5SYY1F4v3+hrHH0MRK+RZUGCeJUqGjDjOdlMlOghEdB3Q7F0Sr2T6/YtySRqj5IefEwblaebVqo9fk5JzflVGrhlNG4VKP/m1zvijDyvukWO8aJ/xHUaRbfX3dz9OX6tvAJkFGaxXmNnzar0LFhFM7vHigN4pwmv6vy12qL4BkTN7rMkfy7jgFtgdWg8Pmqcl6yAEDr3Fsi6KsC0csKcI8okqieJSOsLwx7jQ6qc1Cq3yebfa+gHHjG28ihZ8XTa01FXRF6sECCgsv4RVC8EQWqCikiBkWiOfYw97eisMNVQUvnmGjcdcXqdjTga7eon7GBjfuK8JcRH73Ea3EuBsqoUSHZY7O8NMjf0Nny+KB/FK7cVRW3gH/38gVMknaacYodmoJMGR+NnlpVrxq431mK0jl+xkpXWAfB15MHmlAqpKRkZ2jmOiYo8Z3xsjV23ni4DUFqHE6hLMgp0I61tBUFVdrdk8/qe9tvZEqpBvVoshypWgSkfR0X4EwuAUaavCvUMh/iBt/LRmuFzSc="

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.7.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.7.1.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart

install:
  - composer install

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer global require "phpunit/phpunit:7.*"

script:
  - bin/run-tests

services:
  - mysql
